In [8]:
import pandas as pd

# 读取数据
df = pd.read_csv('data/sales.csv',usecols=['订单号','产品类别', '产品名称', '销售数量', '单价'])

# 数据处理
df['销售金额'] = df['销售数量'] * df['单价']

# 写入数据(index=False表示不写入行索引)
df.to_csv('data/sales_01.csv', index=False)

In [ ]:
# 数据查看 -> head, tail, describe, info, shape, colums
df1 = pd.read_csv('data/sales.csv',usecols=['订单号','产品类别', '产品名称', '销售数量', '单价'])

df1.head(10) # 显示前10行数据(不填默认为前5行)
df1.tail(10) # 显示后10行数据(不填默认为后5行)
df1.describe() # 显示数据的统计信息
df1.info() # 显示数据的结构信息(列名，数据类型，非空值个数，内存使用情况)
df1.shape # 显示数据的维度信息(行数，列数)
df1.columns # 显示数据的列名

In [20]:
df2 = pd.read_csv('data/sales.csv',usecols=['订单号','产品类别', '产品名称', '销售数量', '单价'])

# 1.选择列
# 1.1 单列
df2['产品类别']
# 1.2 多列
df2[['产品类别', '产品名称']]

# 2.选择行 iloc, loc
# 2.1 iloc -> 基于行号选择，不包含stop 语法：iloc[start:stop:step]
df2.iloc[0:3:1] # 选择前3行数据
df2.iloc[0:3]

# 2.2 loc -> 基于行标签,即索引选择，包含stop 语法：loc[start:stop:step]
df2.loc[0:4:1] # 选择前3行数据

          订单号  产品类别  产品名称  销售数量   单价
0  6805677496  家居用品    枕头    10  199
1  5857234132    食品    海苔     5   29
2  5888085059  电子产品  智能音箱     5  399
3  6823473137    食品    面包     3   29
4  6801664364    食品    薯片     2   19

In [27]:
df3 = pd.read_csv('data/sales.csv')

# 数据过滤
# 获取销售数量 >= 7的订单数据
df3[df3['销售数量'] >= 7]

# 获取产品类型为 食品 或 图书 的订单数据
df3[(df3['产品类别'] == '食品') | (df3['产品类别'] == '图书')]
df3[df3['产品类别'].isin(['食品', '图书'])]

# 获取单价在100-200之间的订单数据
df3[(df3['单价'] >= 100) & (df3['单价'] <= 200)]
df3[df3['单价'].between(100, 200)] # 包含边界 
df3[df3['单价'].between(100,200, inclusive="right")] # inclusive right 只包含右边界

# 获取 销售数量>=8, 并且单价>=100的订单数据
df3[(df3['销售数量'] >= 8) & (df3['单价'] >= 100)]

# 获取产品类型为 食品 或 图书, 支付方式为 支付宝或微信的订单数据
df3[(df3['产品类别'].isin(['食品', '图书'])) & (df3['支付方式'].isin(['支付宝', '微信支付']))]

            订单号 产品类别 产品名称  销售数量  单价 客户所在城市  支付方式        订单日期
4    6801664364   食品   薯片     2  19    NaN  微信支付  2025/06/02
9    5888085066   图书   字典     2  99     青岛  微信支付  2025-06-04
10   5808071569   食品  矿泉水     9  29     重庆   支付宝  2025-06-04
13   6880065056   图书  练习册     8  39     深圳   支付宝  2025-06-04
16   5812573980   食品   坚果     2  79     南京  微信支付  2025-06-05
..          ...  ...  ...   ...  ..    ...   ...         ...
980  5825695022   图书  科普书     9  59     长沙   支付宝  2026-03-15
989  6879395963   图书  散文集     4  59     长沙   支付宝  2026-03-18
995  5887473055   图书   小说    10  49     长沙  微信支付  2026-03-20
996  5808511756   食品   坚果     2  79     成都   支付宝  2026-03-20
998  6876456690   食品   果汁     7  39     广州   支付宝  2026-03-20

[276 rows x 8 columns]