In [6]:
import pandas as pd

df = pd.read_csv('data/sales.csv')

# 排序
# 1. 根据销售数量倒序排序
df.sort_values('销售数量', ascending=False)

# 2. 根据单价升序排序
df.sort_values('单价')

# 3.先根据单价升序排序，再根据销售数量倒序排序
df.sort_values(['单价','销售数量'], ascending=[True, False])

            订单号  产品类别   产品名称  销售数量    单价 客户所在城市  支付方式        订单日期
6    6857752388    服装     袜子     7   -29     郑州    现金  2025-06-02
585  6840013941    食品     薯片    10    19     青岛  微信支付  2025-11-23
603  6888122019    食品     薯片     9    19     重庆   支付宝  2025-11-28
97   6847661479    食品     薯片     8    19     重庆   支付宝  2025-06-27
293  5832560118    食品     薯片     7    19     北京   支付宝  2025-08-25
..          ...   ...    ...   ...   ...    ...   ...         ...
149  5846265329  家居用品     床垫     3  5999     合肥   银行卡  2025-07-12
131  5866179578  电子产品  笔记本电脑     2  5999     深圳  微信支付  2025-07-06
715  5859035831  家居用品     床垫     2  5999     昆明   银行卡  2025-12-29
843  5873751742  家居用品     床垫     2  5999     广州   银行卡  2026-02-03
47   5823379341  电子产品  笔记本电脑     1  5999     武汉   银行卡  2025-06-13

[1000 rows x 8 columns]

In [19]:
df = pd.read_csv('data/sales.csv', nrows=20)

#3．分组 
# 3.1 根据 产品类别 分组，统计各个类别的 订单数量 - count
df.groupby('产品类别')['订单号'].count()

# 3.2 根据 产品类别 分组，统计各个类别的 销售数量 之和 - sum
df.groupby('产品类别')['销售数量'].sum()

# 3.3 根据 产品类别 分组，统计各个类别的 销售金额 之和 - sum  
df['销售金额'] = df['销售数量'] * df['单价']
df.groupby('产品类别')['销售金额'].sum()

# 3.4 根据 产品类别 分组，统计各个类别的最低商品 单价 - min
df.groupby('产品类别')['单价'].min()

# 3.5 根据 产品类别 分组，统计各个类别的最高商品 单价 - max
df.groupby('产品类别')['单价'].max()

# 3.6 根据 产品类别 分组，统计各个类别的平均商品 单价 - mean
df.groupby('产品类别')['单价'].mean().round(2)

# 3.7根据 产品类别 分组，统计各个类别的商品的 平均单价、最高单价、最低单价 - mean, max, min
res = df.groupby('产品类别')['单价'].agg(['mean', 'max', 'min'])
res['mean'] = res['mean'].round(2)
res
df.groupby('产品类别').agg({'单价': ['mean', 'max', 'min']})

# 3.8 根据 产品类别 分组，统计各个类别的商品的 销售数量 之和，销售金额 之和，平均单价 - sum, mean
df.groupby('产品类别').agg({'销售数量': 'sum', '销售金额': 'sum', '单价': 'mean'})

      销售数量  销售金额          单价
产品类别
图书      25  1115   51.000000
家居用品    26  4274  149.000000
服装      23  4981  189.666667
电子产品    27  6943  246.500000
食品      21   689   37.000000